- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
    homebrew_taps:
      - caskroom/cask

    homebrew_packages:
      - { name: automake }
      - { name: cmake }
      - { name: ctags }
      - { name: direnv }
      - { name: docker }
      - { name: docker-machine }
      - { name: fontforge }
      - { name: grep }
      - { name: htop }
      - { name: homebrew/dupes/grep }
      - { name: icu4c }
      - { name: imagemagick }
      - { name: libtool }
      - { name: lua }
      - { name: luajit }
      - { name: mas }
      - { name: memcached }
      - { name: mercurial }
      - { name: mysql }
      - { name: neovim }
      - { name: nkf }
      - { name: openssl }
      - { name: peco }
      - { name: pstree }
      - { name: python }
      - { name: python3 }
      - { name: reattach-to-user-namespace }
      - { name: rmtrash }
      - { name: ssh-copy-id }
      - { name: the_silver_searcher }
      - { name: tig }
      - { name: tmux }
      - { name: wget }
      - { name: zlib }

    homebrew_cask_packages:
      - { name: alfred }
      - { name: appcleaner }
      - { name: bettertouchtool }
      - { name: caffeine }
      - { name: dropbox }
      - { name: evernote }
      - { name: firefox }
      - { name: flux }
      - { name: gyazo }
      - { name: google-chrome }
      - { name: google-japanese-ime }
      - { name: iterm2 }
      - { name: keyboardcleantool }
      - { name: macid }
      - { name: skype }
      - { name: slack }
      - { name: the-unarchiver }
      - { name: vagrant }
      - { name: virtualbox }
      - { name: vlc }
      - { name: xquartz }

    mas_packages:
      - { name: 1Password, id: 443987910 }
      - { name: Xcode, id: 497799835 }

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'

    - name: homebrew cask packages install
      homebrew_cask:
        name: "{{ item.name }}"
        state: '{{ item.state | default("present") }}'
      environment:
        HOMEBREW_CASK_OPTS: '--appdir=/Applications'
      with_items: '{{ homebrew_cask_packages }}'
      ignore_errors: true

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'

    - name: install mas (App Store) packages
      shell: mas install "{{ item.id }}"
      with_items: "{{ mas_packages }}"
      register: ret
      changed_when: '"already installed" not in ret.stdout'
