- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - { role: package, tags: [ package ] }
    - { role: osx, tags: [ osx ] }
    - { role: rbenv, tags: [ rbenv ] }
    - { role: dotfiles, tags: [ dotfiles ] }
    - { role: karabiner, tags: [ karabiner ] }
