- hosts: all
  connection: local
  gather_facts: no
  roles:
    - { role: package, tags: [ package ] }
    - { role: osx, tags: [ osx ] }
    - { role: rbenv, tags: [ rbenv ] }
    - { role: nodenv, tags: [ nodenv ] }
    - { role: dotfiles, tags: [ dotfiles ] }
    - { role: karabiner, tags: [ karabiner ] }
