---
- name: Update homebrew
  homebrew:
    update_homebrew: yes

- name: Tap homebrew
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items: '{{ homebrew_taps }}'

- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ item.name }}"
    state: '{{ item.state | default("present") }}'
  environment:
    HOMEBREW_CASK_OPTS: '--appdir=/Applications'
  with_items: '{{ homebrew_cask_packages }}'
  ignore_errors: true

- name: Install homebrew packages
  homebrew:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
  with_items: '{{ homebrew_packages }}'

- name: Install mas (App Store) packages
  shell: mas install "{{ item.id }}"
  with_items: "{{ mas_packages }}"
  register: ret
  changed_when: '"already installed" not in ret.stdout'
