---
- name: Update homebrew
  homebrew:
    update_homebrew: yes

- name: Tap homebrew
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items: '{{ homebrew_taps }}'

- name: Allow apps to be downloaded from anywhere
  shell: spctl --master-disable
  become: yes

- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ item.name }}"
    state: present
  environment:
    HOMEBREW_CASK_OPTS: '--appdir=/Applications'
  with_items: '{{ homebrew_cask_packages }}'

- name: Install homebrew packages
  homebrew:
    name: '{{ item.name }}'
    state: present
  with_items: '{{ homebrew_packages }}'

- name: Install mas (App Store) packages
  shell: mas install "{{ item.id }}"
  with_items: "{{ mas_packages }}"
  register: ret
  changed_when: '"already installed" not in ret.stdout'

- name: Install imgcat
  get_url:
    url: https://iterm2.com/utilities/imgcat
    dest: /usr/local/bin/imgcat
    owner: '{{ owner }}'
    group: '{{ group }}'
    mode: a+x

- name: Don't Allow apps to be downloaded from anywhere
  shell: spctl --master-enable
  become: yes
